### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by asiimwedismas** [emasdev/smithemas_youtube_webpage#3]
Code review for Emanuel

-Change the div with class main to <main> element
-Change the div with classnav to a nav element
-Change the iframe for the video to a video element

**Comment by SigmaSam** [comment]
Code review for Emanuel.

-fix the nav bar to the top with css.

**Comment by shubhsk88** [comment]
-Change the padding to like buttons 
-Give some margin to the right to video
-Add some alt tag in  images for the Search observation
-Add the hamburger and avatar button

**Comment by asiimwedismas** [comment]
-some elements are outside the head element,... fix those, remember everything in a page is inside either the head or body tags,
- Dont forget to validate your page

**Comment by emasdev** [comment]
> Code review for Emanuel
> 
> -Change the div with class main to
> 
> element
> -Change the div with classnav to a nav element
> -Change the iframe for the video to a video element
